---

- hosts: all
  become: true

  vars:
    interface: eth0
    client_net: 10.111.111
    client_net_middleman_ip: "{{ client_net }}.1"
    gate_net: 10.222.222
    gate_net_middleman_ip: "{{ gate_net }}.1"
    gate_net_gate_ip: "{{ gate_net }}.2"
    wg_port: 51820

  tasks:
  - name: Install WireGuard
    apt:
      name: wireguard
      state: present
      update_cache: true

  - name: Generate private and public keys for the client and server
    shell: umask 077; wg genkey | tee {{ item.private }} | wg pubkey > {{ item.public }}
    with_items:
      - { private: server_private_key, public: server_public_key }
      - { private: client_private_key, public: client_public_key }

  - name: Register the key file contents
    command: cat {{ item }}
    register: key_files
    with_items:
      - server_private_key
      - server_public_key
      - client_private_key
      - client_public_key

  - name: Assign the keys to their variables
    set_fact:
      server_private_key: "{{ key_files.results[0].stdout }}"
      server_public_key: "{{ key_files.results[1].stdout }}"
      client_private_key: "{{ key_files.results[2].stdout }}"
      client_public_key: "{{ key_files.results[3].stdout }}"

  - name: Generate server config
    template:
      src: "templates/wg0-server.conf"
      dest: "/etc/wireguard/wg0.conf"
      owner: root
      group: root
      mode: 0600

  - name: Generate client config
    template:
      src: "templates/wg0-client.conf"
      dest: "{{ lookup('env', 'HOME') }}/wg0.conf"
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: 0600

  - name: Enable and start WireGuard interface
    systemd:
      name: wg-quick@wg0
      enabled: yes
      state: started

  - name: Enable IPv4 traffic forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Enable IPv4 forwarding continued
    command: echo 1 > /proc/sys/net/ipv4/ip_forward

  - name: Add route table middleman
    lineinfile:
      path: /etc/iproute2/rt_tables
      line: '1 middleman'

  - name: Set up firewall rules
    include: firewall.yml

  - name: Reboot the server
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true

    - name: Download and install WireGuard UI
      shell: >
        wget https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.6.1/wireguard-ui-v0.6.1-linux-amd64.tar.gz &&
        tar -xvzf wireguard-ui-v0.6.1-linux-amd64.tar.gz &&
        mkdir -p /opt/wireguard-ui &&
        mv wireguard-ui /opt/wireguard-ui/
      args:
        chdir: "/tmp"

    - name: Create WireGuard UI systemd service file
      copy:
        dest: /etc/systemd/system/wireguard-ui-daemon.service
        content: |
          [Unit]
          Description=WireGuard UI Daemon
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          Group=root
          Type=simple
          WorkingDirectory=/opt/wireguard-ui
          ExecStart=/opt/wireguard-ui/wireguard-ui

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start WireGuard UI Daemon
      systemd:
        name: wireguard-ui-daemon
        state: started
        enabled: yes


    - name: Create wgui.service file
      copy:
        dest: /etc/systemd/system/wgui.service
        content: |
          [Unit]
          Description=Restart WireGuard
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/systemctl restart wg-quick@wg0.service

          [Install]
          RequiredBy=wgui.path

    - name: Create wgui.path file
      copy:
        dest: /etc/systemd/system/wgui.path
        content: |
          [Unit]
          Description=Watch /etc/wireguard/wg0.conf for changes

          [Path]
          PathModified=/etc/wireguard/wg0.conf

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start wgui.{path,service}
      systemd:
        name: wgui.{{ item }}
        state: started
        enabled: yes
      loop:
        - path
        - service
